language: node_js
node_js:
- '0.10'
- '0.12'
- iojs
before_install: npm install -g gulp
install: npm install
before_script: gulp lint
script: gulp test
before_deploy: gulp package
deploy:
  provider: releases
  api_key:
    secure: HllmOJmAHfVtIF9tsno+TUFkVpu+gxu6iMBB6jj9fGTJjMl2eXc42zaD8nj37cnXNpk+TkRvOdMygj7goVbLkg0ZP4kJOb81FGBzi9Q3Qd0dyMAOIWDxTsGKrxS3zo/KUUcNCtZQwx3jXEcCWINvFtmvgKS4XuF3GyVsw/TgEoE=
  file: tmp/releases.tar.gz
  on:
    repo: inakianduaga/log-proxy-server
    tags: true
    all_branches: true
    node: '0.12'
after_success:
- gulp coveralls
